## Método de Classificação

In [27]:
from sklearn.neighbors import NearestCentroid # importando o classificador
from sklearn.datasets import make_classification
import pandas as pd

In [28]:
X,y = make_classification(n_samples=100, 
                          n_features=10, 
                          n_informative=5,
                          n_redundant=5,
                          n_classes=3, 
                          weights=[.2,.3,.8]) # Criando dados para classificação

In [30]:
df = pd.DataFrame(X)
df

0         1         2         3         4         5         6  \
0   3.104069 -1.194625  3.697061  0.445603 -1.844241  0.506878  0.873470   
1   0.746822 -1.518468  3.548002  1.475839 -0.835393  0.916444  1.750556   
2   0.767542  1.002743 -4.931952  0.851429 -2.311636 -4.320033 -1.258448   
3   0.948358 -0.282912  1.728514 -1.786941  1.507440  2.665408 -0.586921   
4   0.843444 -2.912575  5.829662 -0.682780  0.417261  1.845350  0.418140   
..       ...       ...       ...       ...       ...       ...       ...   
95 -0.839165  0.680886 -2.200484  0.452000 -0.618106 -1.993049 -0.334566   
96 -3.713210  2.205512 -1.447347  1.925537 -0.255308 -1.556903  1.904535   
97  0.127684 -0.637814  0.051541  2.458975 -1.919512 -1.749876  1.370640   
98  1.136673  1.177405  2.047018  0.432825 -1.772691 -0.490160  1.240854   
99  2.202870  1.101724  1.533106  0.224004 -1.995948 -0.414291  0.819877   

           7         8         9  
0  -2.719499  1.135675 -1.056126  
1  -0.850173 -0.635842 -0.369072  
2  -1.279753  3.995177  0.246743  
3  -0.143523 -2.425602  0.381564  
4  -2.533324 -1.915091 -2.255492  
..       ...       ...       ...  
95  0.276066  1.806365 -0.300268  
96  3.768141  2.607606 -0.815599  
97 -0.558131  1.509329  0.079543  
98 -0.301771  3.678816 -2.006929  
99 -0.945260  3.473813 -1.332091  

[100 rows x 10 columns]

In [31]:
clf=NearestCentroid() #Criando o Classificador

In [32]:
clf.fit(X,y)# Treinando o classificador

NearestCentroid(metric='euclidean', shrink_threshold=None)

In [33]:
clf.predict([[0,0,0,0,0,1,1,1,1,1]]) #Realizando a predição 

array([0])

## Método de regressão

In [42]:
from sklearn.datasets import make_regression
from sklearn import svm
import pandas as pd

In [47]:
X, t, coef = make_regression(n_samples=100, 
                                         n_features=3, 
                                         n_informative=2, # Quantas features, influenciarão no Y, ou seja, estão correlacionados 
                                         n_targets=1, # Quantos Y ?
                                         noise=0.0,
                                         coef=True
                                        )

In [48]:
df = pd.DataFrame(X, columns=['Store 1', 'Store 2', 'Store 3'])
df

Store 1   Store 2   Store 3
0   2.139303 -0.582862  0.505481
1   0.021942  1.234319  0.331884
2   1.130403 -1.240146 -0.540861
3  -0.944683  0.084041  1.123645
4  -2.017520  1.840628  0.729810
..       ...       ...       ...
95  1.120050 -0.309553 -0.726085
96 -0.023311 -1.886449  1.752523
97 -0.488112  2.213759  1.084567
98  0.127490 -1.922203  0.028092
99 -1.656168  1.073210  1.408673

[100 rows x 3 columns]

In [49]:
reg=svm.SVR() # Criando modelo de regressão

In [50]:
reg.fit(X,y) # Treinando o modelo de regressão

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [51]:
reg.predict([[0,0,1]]) # Realizando a predição

array([1.35672858])

## Perceptron

In [53]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [69]:
iris = datasets.load_iris() #Carrega o dataset de Íris

In [70]:
# Cria o X e y
X = iris.data
y = iris.target

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [72]:
sc=StandardScaler()
X_train_std = sc.fit_transform(X_train) #ajustes de escala usando os dados de treino
X_test_std = sc.fit_transform(X_test) #ajustes de escala usando os dados de test

In [85]:
ppn = Perceptron(tol=1e-3, random_state=0) #Cria o perceptron
ppn.fit(X_train_std, y_train) # Ajusta o Perceptron com os dados de treino

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [82]:
y_predicted = ppn.predict(X_test_std) # realiza a predição

In [83]:
print(accuracy_score(y_test, y_predicted))

0.9555555555555556


### Salvando a Predição

In [90]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
import pickle
from sklearn.externals import joblib

In [94]:
# recarga dos datasets
iris = datasets.load_iris()
X, y = iris.data, iris.target

In [96]:
clf = LogisticRegression()
clf.fit(X, y)  

D:\paulo\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [97]:
saved_model = pickle.dumps(clf)
saved_model

b'\x80\x03csklearn.linear_model._logistic\nLogisticRegression\nq\x00)\x81q\x01}q\x02(X\x07\x00\x00\x00penaltyq\x03X\x02\x00\x00\x00l2q\x04X\x04\x00\x00\x00dualq\x05\x89X\x03\x00\x00\x00tolq\x06G?\x1a6\xe2\xeb\x1cC-X\x01\x00\x00\x00Cq\x07G?\xf0\x00\x00\x00\x00\x00\x00X\r\x00\x00\x00fit_interceptq\x08\x88X\x11\x00\x00\x00intercept_scalingq\tK\x01X\x0c\x00\x00\x00class_weightq\nNX\x0c\x00\x00\x00random_stateq\x0bNX\x06\x00\x00\x00solverq\x0cX\x05\x00\x00\x00lbfgsq\rX\x08\x00\x00\x00max_iterq\x0eKdX\x0b\x00\x00\x00multi_classq\x0fX\x04\x00\x00\x00autoq\x10X\x07\x00\x00\x00verboseq\x11K\x00X\n\x00\x00\x00warm_startq\x12\x89X\x06\x00\x00\x00n_jobsq\x13NX\x08\x00\x00\x00l1_ratioq\x14NX\x08\x00\x00\x00classes_q\x15cnumpy.core.multiarray\n_reconstruct\nq\x16cnumpy\nndarray\nq\x17K\x00\x85q\x18C\x01bq\x19\x87q\x1aRq\x1b(K\x01K\x03\x85q\x1ccnumpy\ndtype\nq\x1dX\x02\x00\x00\x00i4q\x1eK\x00K\x01\x87q\x1fRq (K\x03X\x01\x00\x00\x00<q!NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq"b\x89C\x0c\x00\x00\x00

In [98]:
clf_from_pickle = pickle.loads(saved_model)

In [99]:
clf_from_pickle.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Exercício dos preços das casas em Boston

In [125]:
import numpy as np
import pandas as pd
import visuals as vs # Supplementary code
from sklearn.model_selection import ShuffleSplit

In [127]:
# Pretty display for notebooks
%matplotlib inline

# Load the Boston housing dataset
data = pd.read_csv('housing.csv')
prices = data['MEDV']
features = data.drop('MEDV', axis = 1)
print('Boston housing dataset has {} data points with {} variables each.'.format(*data.shape))

Boston housing dataset has 489 data points with 4 variables each.


In [128]:
features.head()

RM  LSTAT  PTRATIO
0  6.575   4.98     15.3
1  6.421   9.14     17.8
2  7.185   4.03     17.8
3  6.998   2.94     18.7
4  7.147   5.33     18.7

In [130]:
minimum_price = np.amin(prices)
maximum_price = np.amax(prices)
mean_price = np.mean(prices)
median_price = np.median(prices)
std_price = np.std(prices)

print ("Statistics for Boston housing dataset:\n")
print ("Minimum price: ${:,.2f}".format(minimum_price))
print ("Maximum price: ${:,.2f}".format(maximum_price))
print ("Mean price: ${:,.2f}".format(mean_price))
print ("Median price ${:,.2f}".format(median_price))
print ("Standard deviation of prices: ${:,.2f}".format(std_price))

Statistics for Boston housing dataset:

Minimum price: $105,000.00
Maximum price: $1,024,800.00
Mean price: $454,342.94
Median price $438,900.00
Standard deviation of prices: $165,171.13


In [131]:
from sklearn.metrics import r2_score

def performance_metric(y_true, y_predict):
    """ Calculates and returns the performance score between 
        true and predicted values based on the metric chosen. """
    score = r2_score(y_true, y_predict)
    return score

In [132]:
score = performance_metric([3, -0.5, 2, 7, 4.2], [2.5, 0.0, 2.1, 7.8, 5.3])
print ("Model has a coefficient of determination, R^2, of {:.3f}.".format(score))

Model has a coefficient of determination, R^2, of 0.923.


In [134]:
from sklearn.model_selection import ShuffleSplit

X_train, X_test, y_train, y_test = train_test_split(features, prices, train_size=0.8, random_state=0)

print("Training and testing split was successful.")

Training and testing split was successful.


In [135]:
vs.ModelLearning(features, prices)

TypeError: __init__() got an unexpected keyword argument 'n_iter'

In [140]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns

def dropColumns(xData,dataset):
	# plot the data
	sns.pairplot(dataset,x_vars=xData.columns.values,y_vars=['medv'])
	plt.show()
	# drop the columns that has no relation with the dependent variable
	xData=xData.drop(columns=['chas','rad','zn','age','tax','b','indus','nox','crim','dis','ptratio'])
	sns.pairplot(dataset,x_vars=xData.columns.values,y_vars=['medv'])
	plt.show()
	return xData
def dataAnalysis(xData,dataset):
	sns.set(rc={'figure.figsize':(11.7,8.27)})
	sns.distplot(dataset['medv'], bins=30)
	plt.show()
	#find the correalted variables
	corelationMatrix=dataset.corr().round(2)
	sns.heatmap(data=corelationMatrix,annot=True)
	plt.show()
	xData=dropColumns(xData,dataset)
	return xData

In [143]:
#read the dataset
dataset=pd.read_csv("housing.csv") # carregando os dados com os preços de boston
# find dependent and independent variables
x=dataset.iloc[:,:-1] # Pegando todas as colunas menos a última (Os valores de x)
y=dataset.iloc[:,-1] # Pegando os valores de Y, somente a última coluna
# x=dataAnalysis(x,dataset)
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=45,train_size=0.7)
lr=LinearRegression()# Criando um modelo de regressão
#fit the train data
lr.fit(x_train,y_train) #treinando o modelo de regressão
#predict for the test data
y_pred=lr.predict(x_test) #Predizendo os valores dos dados de teste
error=mean_squared_error(y_test,y_pred) #calculando o erro da regressão
print("The Mean squared error is {:.4f}".format(error)) #imprimindo o erro

The Mean squared error is 24.4611
